### PR TITLE
Add check for originalEvent on touch events

### PR DESCRIPTION
**Pull request by alexdrans**
Thanks for creating this, @twhitbeck, it's exactly what I needed. I've made a change to overcome an issue I had in using the directive. On mobile, the touch event is exposed via originalEvent.

### CODE REVIEW

**Comment by alexdrans** [comment]
If this is merged in, when will it be available on NPM?

**Comment by shriramcs** [comment]
HI, i'm also facing this issue, can you please push this to master ? when can we expect this fix? i'm facing bug in production, kindly do the needfull. thanks in advance.

**Comment by alexdrans** [comment]
Why don't you fork in the meantime?

**Comment by twhitbeck** [comment]
Thanks for the feedback. I did a little digging into this issue:

originalEvent is a jQuery thing. According to documentation: http://api.jquery.com/category/events/event-object/ the `touches` event property is not copied over to jQuery's event wrapper object. Therefore you need to go through `e.originalEvent` to get to the `touches` property. I'll merge your changes

**Comment by shriramcs** [comment]
@twhitbeck Thanks a lot for your quick response.

**Pull request merged**
